
# https://docs.travis-ci.com/user/languages/dart/

language: dart
# os: osx
dart:
  - stable

install:
  - git clone https://github.com/flutter/flutter.git --depth 1
  - export PATH=$(pwd)/flutter/bin:$PATH

before_install:
  - chmod +x ./android_build ./ios_build

jobs:
  include:
    # produces: build/app/outputs/apk/app-release.apk
    - script: ./android_build

# safelist of branches to build
branches:
  only:
    - release