language: objective-c
os: osx
osx_image: xcode9.1
install:
- brew tap dart-lang/dart
- brew install dart
- chmod +x ./android_build ./ios_build
- git clone https://github.com/flutter/flutter.git --depth 1
- export PATH=$(pwd)/flutter/bin:$PATH
- flutter doctor
jobs:
  include:
  - script: "./ios_build_full.sh"
branches:
  only:
  - release
deploy:
  provider: s3
  access_key_id: AKIAJZWITJFXNAITFJPA
  bucket: tbs-bible-app
  skip_cleanup: true
  local_dir: build/ios/iphoneos
  region: eu-west-1
  on:
    branch: release
  secret_access_key:
    secure: "Ad6TN+QSrAmrkTkKPHSeqp6hTKouHCZSMiGxDwk7Y1eI/LQRFg71ZdEOl/7E0w70FkPBQSUT/jcGnetMs2e9A+sst7Z9V0Y++U37SZ4ttqGJyR5Tc0vs849Jf8sRO0tlFFRy21BIXcZpYB2qgC64dgXU++yIuxgR+i0cWRPaFBQ/fwZNw9z6GAMrWsc5XV9y+rLeCY6MKizmsbLQnZkOgTQlJNNC8l+vxP0qy5irX8/7/InEfhT7uWQjAT4BLwaK7lalHVlUdCDXOSCDvEo2Pm/A2vZe7hgM9a4vvZcxU/y7aprWEN2MbcaW/Nq3tar3UblMNWgwvvch74KOKbQKzjFi8+6qL4Gahu5KAWglDd6VKL369DICDwz+1BHMjSSjM0sPK0XtJP2R0dZKvunms6zU8o9jYlLsTFMuWKonjLchSY7dXsTawQ+dovEEa1vi9+gXC5gTY6+fPCIiU2sxN+e7RV2vZhsu6pBu1Q9T3B9gahl4DX2g3X2p/rDdUoWckaWe/nD0ebNFxgxEDiuks2L2a5xGzLZSp4wugWyUg7ngaDQyiBQ9QvpzusPF/r5dYfM7kU0PpOPj6QQbVyj9UJwvhhuMK9CIQPowgvSgJLcz8X/pW2/+F6wM0KLvGtJDo7ngDVU4pHQYgtRbbbJMxGVE0qKykkIUCsq9CM+V3WE="

env:
  global:
    secure: "iJj2RdtfY+mBu8dudGDQAdZUM8PYr4J5ZDvpuFcD1/yYm2midvcnk4aZPOHnmB0HgQJCraRtxglB90zMgEkxM6tIhTL/SjHZqYnDuic0SOkGJq5e7hJo+9ee4LTfQ3CZ1r9+TS/sAI+j5TbqSNbw786hQC5l3uRHFvY7mnEEqreHVe60gddai7Ie3paImC824CEwjkVlJ580ElISivI+Ns2Di9M0VcOqyu8S2kc+YlqGfUnqvGIqz9iBGwRMearioE48P1nCrd43C2WrB2q7uIcUDeP0eX1VtL5v9SrzjsGTKcmVzBh7e0jfvGvipI8a05h97FmU1mec/gM5jOw1UHohO4snl2CT1rSuv8zPfrGjyRAiad6XxkJHFBrxCYOzeTaKK/GtdYfZoabo5AycugSo/IpWllwFi4xMoGcsR0ndWvgm19aHl/2nWnJUdJhP/6UfmPRJDjq/kKOlo9Rxegh3kUTRWRo7KVsm4VksEmHOTACTHCHXa/XY4YVhlizU7zSlzmckOP6WyX/tLK7fOYW1SxyLq7I5VCzg5u6b7Hn2jvmNOCYEzvUDQnaQ6J/9Zlozt/Z5CuflxXiQg2rto74GmV8DSGhym0nVocRAGC+ksv6x16Pd0BZMGcQPx0UqtbeUXdOhWC7cAVROsoRElSzb8pjaURw87ZMVZb2h0Gk="
