
# https://docs.travis-ci.com/user/languages/dart/

# useful:
# https://github.com/flutter/posse_gallery/blob/master/.travis.yml

#language: dart
language: android
# language: objective-c

os: osx

install:
  - git clone https://github.com/flutter/flutter.git --depth 1
  - export PATH=$(pwd)/flutter/bin:$PATH
  - flutter doctor

before_install:
  - brew tap dart-lang/dart
  - brew install dart
  - chmod +x ./android_build ./ios_build
  #- chmod +x ./install_android
  #- ./install_android

jobs:
  include:
    # produces: build/app/outputs/apk/app-release.apk
    - script: ./android_build

# safelist of branches to build
branches:
  only:
    - release
    